version: '3.8'
services:
  springboot_app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecom_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: mysecretkey
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: ecom_postgres
    environment:
      POSTGRES_DB: ecom_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
